<a href="https://colab.research.google.com/github/Mapuertag/Datascience300/blob/main/Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import os
drive.mount('/content/gdrive')
import os
print(os.getcwd())
#os.chdir("/content/gdrive/MyDrive")
print(os.getcwd())


Mounted at /content/gdrive
/content
/content


In [ ]:
%cd "/content/gdrive/MyDrive/UNIVERSIDAD/Practicas"

/content/gdrive/MyDrive/UNIVERSIDAD/Practicas


## Ejercicio 1

Creen un vector a entre 5 y 6 con intervalo de 0.2 y guardenlo en formato datos.npy y luego carguenlo con nombre b y muéstrelo

In [ ]:
import numpy
a=numpy.arange(5,6.1,0.2)
print(a.tolist())
a.tofile("datos.dat")
b=numpy.fromfile("datos.dat")
b


[5.0, 5.2, 5.4, 5.6000000000000005, 5.800000000000001, 6.000000000000001]


array([5. , 5.2, 5.4, 5.6, 5.8, 6. ])

## Ejercicio 2

Cree un una matriz A con ```np.array```

$$\begin{bmatrix} 
	1 & 3 & 5 \\
	11 & 9 & 7\\
	13 & 15 & 17 \\
	\end{bmatrix}$$

Luego de eso utilize el metodo ```np.sort``` con  el argumento ```axis =1``` or ```axis=0```

A que conclusiones llegan? 

In [ ]:
import numpy as np
A=np.array([[1,3,-5],[11,9,5],[13,15,17]])
B=np.sort(A, 0)
C=np.sort(A, 1)
print("Matriz A virgen")
print(A)
print(".....")
print("Matriz B, axis=0")
print(B)
print(".....")
print("Matriz C, axis=1")
print(C)


Matriz A virgen
[[ 1  3 -5]
 [11  9  5]
 [13 15 17]]
.....
Matriz B, axis=0
[[ 1  3 -5]
 [11  9  5]
 [13 15 17]]
.....
Matriz C, axis=1
[[-5  1  3]
 [ 5  9 11]
 [13 15 17]]


## Ejercicio 3

Cree una matriz de 3x3 B, como la siguiente:

$$\begin{bmatrix} 
	9 & 1 & 2 \\
	1 & 9 & 5\\
	2 & 5 & 9 \\
	\end{bmatrix}$$

1. Convierta la matriz a un vector de 1x9
2. Ordene de de menor a mayor el vector
3. Aplique un filtro para extraer solo los numeros menores que 9

In [ ]:
import numpy as np
B=np.array([[9,1,2],[1,9,15],[2,5,9],[2,5,9]])
print(B)
print(".........................")
print("solucion 1")
v1=np.reshape(B, 12)
print(v1)
v2=np.sort(v1, 0)
print(".........................")
print("solucion 2")
print(v2)
condicion=np.where(v1<9, 1, 0)
v3=np.extract(condicion,v1)
print(".........................")
print("condicion")
print(condicion)
print(".........................")
print("solucion 3")
print(v3)

[[ 9  1  2]
 [ 1  9 15]
 [ 2  5  9]
 [ 2  5  9]]
.........................
solucion 1
[ 9  1  2  1  9 15  2  5  9  2  5  9]
.........................
solucion 2
[ 1  1  2  2  2  5  5  9  9  9  9 15]
.........................
condicion
[0 1 1 1 0 0 1 1 0 1 1 0]
.........................
solucion 3
[1 2 1 2 5 2 5]


## Ejercicio 4

Cree una matriz de 3x3 C, como la siguiente:

$$\begin{bmatrix} 
	1 & 4 & 7 \\
	2 & 5 & 8\\
	3 & 6 & 9 \\
	\end{bmatrix}$$

1. Calcule la media por cada columna
2. Calcule la media por cada fila
3. Obtenga la media por columnas dandole el doble de peso a la columna con mayores valores de la variable
4. Calcule el percentil 25 por cada columna

In [ ]:
import numpy as np
C=np.array([[9,1,2,1],[1,9,15,2],[2,5,9,3],[2,5,9,4]])
print(C)
print(".........................")
print("solucion 1")
C1=np.mean(C, 0)
print(C1)
print(".........................")
print("solucion 2")
C2=np.mean(C, 1)
print(C2)
print(".........................")
print("solucion 3")
C3=np.average( C, 0, weights=( 1,1,2,1)) # por favor explicar
print(C3)
print(".........................")
print("solucion 4")
C4=np.percentile(C, 25, 0)
print(C4)



[[ 9  1  2  1]
 [ 1  9 15  2]
 [ 2  5  9  3]
 [ 2  5  9  4]]
.........................
solucion 1
[3.5  5.   8.75 2.5 ]
.........................
solucion 2
[3.25 6.75 4.75 5.  ]
.........................
solucion 3
[3.2 5.  8.8 2.6]
.........................
solucion 4
[1.75 4.   7.25 1.75]


## Ejercicio 5

Carguen la imagen data_science que se encuentra en el siguiente link: [texto del enlace](https://drive.google.com/file/d/1LoGybQ8t9g6orVp8Wh0uqU7BXY0kCzlh/view?usp=sharing) en la semana 1 del Bootcamp y realicen los siguientes procedimientos

1. Muestrar la imagen tal como viene
2. Averiguen que es un pixel y determinen cuantos pixeles tiene la imagen
3. Recortar la imagen donde solo aparezca la palabra DATA
4. Convertir la imagen a matriz y aplicar la funcion coseno
5. Reemplazar los valores menores que 100 en la imagen original por 180 y graficar ¿Que observan, que modificaciones ocurrieron y porgque?. **Sugerencia:** *Busquen acerca de que es la escala RGB y seguro comprenderan mejor*

In [ ]:
from google.colab import drive
import os
drive.mount('/content/gdrive',True)

Mounted at /content/gdrive


### **Ejercicios Semana 2**




## Ejercicio 1 : Listas

Tienen la siguiente lista🏀⚾⚽🥤⭐

```list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]```

Se desea obtener el siguiente output **pero** usando solo el metódo ```append```:

```[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]```

In [ ]:
mylist= [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
mylist[2][2].append(7000)
print(mylist)

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]


## Ejercicio 2 : Sets
Dados los siguientes conjuntos⛹✅☁⚽✨

```s1 = {10, 20, 30, 40, 50}```

```s2 = {30, 40, 50, 60, 70}```

1. Como es posible obtener el siguiente output con alguno de los metódos vistos para sets

```{40, 50, 30}```

2. Como es posible obtener el siguiente output con alguno de los metódos vistos para sets

```{70, 40, 10, 50, 20, 60, 30}```

3. Extraer todos los elementos de s2 que no estan en s1

In [ ]:
s1 = {10, 20, 30, 40, 50}
s2 = {30, 40, 50, 60, 70}
print("solucion 1")
print(s1.intersection(s2))
print("..................")
print("solucion 2")
print(s1.union(s2))
print("..................")
print("solucion 3")
print(s2.symmetric_difference(s1))

solucion 1
{40, 50, 30}
..................
solucion 2
{70, 40, 10, 50, 20, 60, 30}
..................
solucion 3
{20, 70, 10, 60}


## Ejercicio 3: Tuplas

Dada la siguiente tupla✈⏰♒⛹

```tupla=(10, 20, 30, 40, 50)```

Responder:

1. Ordenar la tupla de mayor a menor
2. Extraer los valores de la tupla en las siguientes variables: a,b,c,d,e
3. Ahora suponga que tiene la siguiente tupla: 
```tupla_d = (11, [22, 33], 44, 55)```
Recordando el concepto de inmutabilidad de las tuplas, sería posible poder modificar el valor **22** por **222** o en este caso no se puede?. Justifiquen